[project]
name = "deteccion-de-caidas"
version = "0.1.0"
description = "Sistema de detección de caídas y señal de ayuda"
readme = "README.md"
authors = [
    { name = "kaz-py", email = "juanmanuelinsaurraldeniven2021@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.14,<0.11.0",
    "numpy>=2.3.5",
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.129",
]

[project.scripts]
deteccion-caidas = "deteccion_de_caidas.main:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
